### ISSUE TITLE
Milestone 2 To-Do List

### ISSUE THREAD

**Issue by BChangs99** [UBC-MDS/DSCI522-2425-25-heart_disease_predictor#19]
Milestone 2: https://pages.github.ubc.ca/MDS-2024-25/DSCI_522_dsci-workflows_students/release/milestone2/milestone2.html
- [x] Setup Dockerfile - Brian + Yeji
- [x] Update README.md on how to use/update the container image - Brian + Yeji
- [x] Data Validation - Celine + Anna

**Comment by TinLattNandar** [comment]
We need to create 
- at least 2 issues per pax 
- run on both machines (mac + windows)
